#ifndef _NETBENCH_PRINTER_TYPE_H
#define _NETBENCH_PRINTER_TYPE_H


enum netbench_printer_type
{
	NETBENCH_PRINTER_MATRIX,
	NETBENCH_PRINTER_HTML,
	NETBENCH_PRINTER_CLASSIC,
	NETBENCH_PRINTER_NONE
};

#endif
