#ifndef _NETBENCH_COMMUNICATION_PROTOCOL_H
#define _NETBENCH_COMMUNICATION_PROTOCOL_H

enum netbench_comm_proto
{
	NETBENCH_COMM_PROTO_ROLE,
	NETBENCH_COMM_PROTO_RANK,
	NETBENCH_COMM_PROTO_RESULT,
	NETBENCH_COMM_PROTO_LIST
};

#endif
